# You should NOT edit this file to change permissions
name: Volt
main: volt\Volt
version: 3.1.0
author: Falkirks
api: [3.0.0-ALPHA5]
load: POSTWORLD
permissions:
 volt:
  default: op
  children:
   volt.command:
    default: op
    children:
     volt.command.api:
      default: true
      children:
        volt.command.api.list:
          default: op
        volt.command.api.getsub:
          default: op
