<?php
namespace httpserver;

use pocketmine\plugin\PluginBase;

class MonitoredWebsiteData extends WebsiteData{

    public function __construct($name, array $page = []){
        $this->name = ($name instanceof PluginBase ? $name->getName() : $name);
        parent::__construct($page);
    }

    public function offsetExists($offset){
        parent::offsetExists($offset); // TODO: Change the autogenerated stub
    }

    public function offsetGet($offset){
        parent::offsetGet($offset); // TODO: Change the autogenerated stub
    }

    public function offsetSet($offset, $value){
        parent::offsetSet($offset, $value); // TODO: Change the autogenerated stub
    }

    public function offsetUnset($offset){
        parent::offsetUnset($offset); // TODO: Change the autogenerated stub
    }

    function __get($name){
        $page = $this->page;
        $page[] = $name;
        return new MonitoredWebsiteData($this->name, $page);
    }
}