<?php
namespace volt\api;

use pocketmine\plugin\PluginBase;
use pocketmine\Server;
use volt\exception\PluginIdentificationException;

class MonitoredWebsiteData extends WebsiteData{

    final public function __construct($name = false){
        if($name == false){
            $trace = debug_backtrace();
            if (isset($trace[1])) {
                $fullClass = explode("\\", $trace[1]['class']);
                $name = array_pop($fullClass);

            }
        }

        if($name instanceof PluginBase) {
            $this->name = $name->getName();
        }
        else{
            if(Server::getInstance()->getPluginManager()->getPlugin($name) instanceof PluginBase){
                $this->name = $name;
            }
        }
        if($this->name == null) throw new PluginIdentificationException;
        parent::__construct();
    }

    public function offsetExists($offset){
        parent::offsetExists($offset); // TODO: Change the autogenerated stub
    }

    public function offsetGet($offset){
        parent::offsetGet($offset); // TODO: Change the autogenerated stub
    }

    public function offsetSet($offset, $value){
        parent::offsetSet($offset, $value); // TODO: Change the autogenerated stub
    }

    public function offsetUnset($offset){
        parent::offsetUnset($offset); // TODO: Change the autogenerated stub
    }
}